hydra:
  run:
    dir: D:/python_course/gym-multigrid/
  sweep:
    dir: D:/python_course/gym-multigrid/
    subdir: ''
  launcher:
    _target_: hydra_plugins.hydra_joblib_launcher.joblib_launcher.JoblibLauncher
    n_jobs: -2
    backend: multiprocessing
    prefer: processes
    require: null
    verbose: 0
    timeout: null
    pre_dispatch: 2*n_jobs
    batch_size: auto
    temp_folder: null
    max_nbytes: null
    mmap_mode: r
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: 1
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: .hydra
  overrides:
    hydra:
    - hydra.mode=MULTIRUN
    task:
    - algorithm=pac_dcg_ns
    - train_epochs=100_000
    - reward=fire_adjacent
    - common_reward=True
    - experiments/team_size=fifteen
    - use_rnn=False
    - experiments/obs=range_six,range_ten,default
    - wandb.enabled=False
    - eval_seed=3456,2004,8007
    - checkpoint=pac_sarsa_dcg_ns_10_13_fire_adjacent_obs_10
    - save_replay=True
    - evaluate=True
    - runner=episode
    - batch_size_run=1
    - batch_size=1
  job:
    name: train_test_wildfire
    chdir: true
    override_dirname: algorithm=pac_dcg_ns,batch_size=1,batch_size_run=1,checkpoint=pac_sarsa_dcg_ns_10_13_fire_adjacent_obs_10,common_reward=True,eval_seed=3456,2004,8007,evaluate=True,experiments/obs=range_six,range_ten,default,experiments/team_size=fifteen,reward=fire_adjacent,runner=episode,save_replay=True,train_epochs=100_000,use_rnn=False,wandb.enabled=False
    id: ???
    num: ???
    config_name: default
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.3.2
    version_base: '1.3'
    cwd: D:\python_course\gym-multigrid
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: D:\python_course\gym-multigrid\configs
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    output_dir: ???
    choices:
      experiments/fire_spread: default
      experiments/team_size: fifteen
      experiments/obs: default
      experiments/env_size: default
      reward: fire_adjacent
      algorithm: pac_dcg_ns
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: joblib
      hydra/output: default
  verbose: false
wandb:
  enabled: false
  entity: vinokur-eg-
  project: Wildfire
  mode: online
use_cuda: false
device: cpu
sb3:
  _target_: algorithm.sb3.train
agilerl:
  _target_: algorithm.agilerl.train
common_reward: true
reward_scalarisation: mean
seed: 3456
eval_seed: null
agents: 15
agents_inference: 15
flashpoints: 3
world_size: 13
alpha_transition: 0.3
beta_transition: 0.8
agent_beta_impact: 0.8
obs_type: typed_one_hot
reward_type: fire_adjacent
agent_view_size: ${world_size}
partial_obs: false
max_steps: 25
cooperative_reward: true
observations:
  false: full
  true: partial_{$agent_view_size}
run_id: ${name}_${agents}_${world_size}_${reward_type}_obs_${agent_view_size}${fire_spread}
training_type: ???
from_scratch: true
evaluate: true
model_save_path: out/models/
checkpoint: pac_sarsa_dcg_ns_10_13_fire_adjacent_obs_10
use_rnn: false
log: out/logs/
train_epochs: 100000
memory_size: 10000
valid_interval: 10000
batch_size_run: 1
episodes: 15
runner: episode
mac: basic_mac
env_args: {}
test_nepisode: ${episodes}
test_interval: ${valid_interval}
test_greedy: true
log_interval: ${valid_interval}
runner_log_interval: ${valid_interval}
learner_log_interval: ${valid_interval}
t_max: ${train_epochs}
buffer_cpu_only: true
use_tensorboard: true
wandb_mode: online
wandb_save_model: true
save_model: true
save_model_interval: ${valid_interval}
checkpoint_path: vdn_10_13_fire_adjacent_obs_10
render: false
load_step: 0
save_replay: true
local_results_path: ${model_save_path}
gamma: 0.99
batch_size: 1
buffer_size: 10
lr: 0.0005
optim_alpha: 0.99
optim_eps: 1.0e-05
grad_norm_clip: 10
add_value_last_step: true
n_agents: ${agents}
n_actions: 4
state_shape: ''
agent: rnn_ns
hidden_dim: 64
obs_agent_id: false
obs_last_action: false
repeat_id: 1
label: default_label
hypergroup: null
action_selector: soft_policies
mask_before_softmax: true
target_update_interval_or_tau: 0.01
obs_individual_obs: false
agent_output_type: pi_logits
learner: pac_dcg_learner
standardise_rewards: false
q_nstep: 10
critic_type: pac_dcg_critic_ns
state_value_type: cv_critic_ns
initial_entropy_coef: 30.0
final_entropy_coef: 0.01
entropy_end_ratio: 0.8
cg_edges: full
cg_utilities_hidden_dim: null
cg_payoffs_hidden_dim: null
cg_payoff_rank: null
duelling: false
msg_anytime: true
msg_iterations: 8
msg_normalized: true
name: pac_sarsa_dcg_ns
on_policy: false
fire_spread: ''
