# @package _global_
defaults:
  - maddpg

name: matd3
algorithm:
  _target_: algorithm.agilerl.model_MATD3
init_hp:
 # "POPULATION_SIZE": 5,
  batch_size: 32 # Batch size
  policy_freq: 2  # Policy frequency

