defaults:
  - _self_
  - algorithm: matd3
  - reward: default
  # - sweeps: wandb
  #   optional: True
  - experiments/env_size: default

  - experiments/team_size: default

  # - override hydra/job_logging: file
  # - override hydra/launcher: submitit_local
  # - override hydra/sweeper: wandb

wandb: 
  enabled: False
  project: Wildfire
device: "cpu"

sb3_callbacks:
  _target_: algorithm.sb3.setup_callbacks

env:
  agents: 5
  agents_inference: 5
  flashpoints: 3
  world_size: 13
  alpha_transition: 0.3
  beta_transition: 0.8
  agent_beta_impact: 0.8
  obs_type: typed_one_hot
  reward_type: default
  partial_obs: False
  cooperative_reward: True

run_id: ${name}_${env.agents}_${env.world_size}
training_type: ???
from_scratch: True
job_type: train
model_save_path: out/models/${run_id}
log: out/logs/wildfire/
train_epochs: 100_000
memory_size: 100_000  # Max memory buffer size
valid_interval: 10000 # Valid frequency during train
episodes: 25