defaults:
  - _self_
  - algorithm: vdn
  - reward: fire_adjacent
  # - sweeper: wandb
  #   optional: True
  - experiments/env_size: default
  - experiments/obs: default
  - experiments/team_size: default
  - experiments/fire_spread: default
  # - override hydra/job_logging: file
  # - override hydra/launcher: submitit_local
  - override hydra/launcher: joblib
  # - override hydra/sweeper: wandb


hydra:
  run:
    dir: 'D:/python_course/gym-multigrid/'
    # dir: 'D:/'
  sweep:
    dir: 'D:/python_course/gym-multigrid/'
    # dir: 'D:/'
    subdir: ''
  launcher:
    # timeout_min: 2880
    # timeout: 2880
    n_jobs: -3
    pre_dispatch: n_jobs

  job:
    chdir: True

wandb: 
  enabled: False
  entity: vinokur-eg-
  project: Wildfire
  mode: online

use_cuda: False  
device: "cpu"

sb3:
  _target_: algorithm.sb3.train

agilerl:
  _target_: algorithm.agilerl.train

common_reward: False  # Run experiment with common reward setup
reward_scalarisation: "sum"  # How to aggregate rewards to single common reward (only used if common_reward is True
seed: 3456
eval_seed: -1
# env:
agents: 7
agents_inference: 5
flashpoints: 3
world_size: 13
alpha_transition: 0.3
beta_transition: 0.8
agent_beta_impact: 0.8
obs_type: typed_one_hot
reward_type: default
agent_view_size: 13
partial_obs: False

cooperative_reward: True

observations: 
  False: full
  True: partial_{$agent_view_size}


run_id: ${name}_${agents}_${world_size}_${reward_type}_obs_${agent_view_size}
training_type: ???
from_scratch: True
evaluate: False
model_save_path: out/models/
checkpoint: ''
log: out/logs/
train_epochs: 100_000
memory_size: 10_000  # Max memory buffer size
valid_interval: 10_000 # Valid frequency during train
batch_size_run: 1 # N of envs to run in parallel
episodes: 5